apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test-app
  name: test-app
  namespace: test-gitops-staging
spec:
  replicas: 3
  template:
    spec:
      containers:
      - image: nginx:1.21.1
        name: nginx
